pool: 
    vmImage: 'Ubuntu-16.04'
    demands:
        npm

variables:
    buildConfiguration: 'Release'
    wwwRootPath: 'Tailspin.SpaceGame.Web/wwwroot'
    dotNetSDKVersion: '2.1.505'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 2.1.505'
  inputs:
    version: '$(dotNetSDKVersion)'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass $(wwwRootPath) --output $(wwwRootPath) '
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: $(wwwRootPath)

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# - template: templates/build.yml
#   parameters:
#     configuration: 'Debug'

# - template: templates/build.yml
#   parameters:
#     configuration: 'Realease'

- task: DotNetCoreCLI@2
  displayName: 'Build Project - $(buildConfiguration)'
  inputs:
    command: build
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/*.csproj'

# Install ReportGenenrator Tool
# - task: DotNetCoreCLI@2
#   displayName: "Install ReportGenerator tool"
#   inputs:
#     command: custom
#     custom: Tool
#     arguments: 'install --global dotnet-reportgenerator-globaltool'

- script: 'dotnet tool install --global dotnet-reportgenerator-globaltool'
  displayName: 'Install Report Generator Tool'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests for $(buildConfiguration)'
  inputs:
    command: 'test'
    arguments: '--no-build --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
    publishWebProjects: false
    projects: '**/*.Tests.csproj'

- script: 'reportgenerator -reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:HtmlInline_AzurePipelines'
  displayName: 'Create Code Coverage Report'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

- task: DotNetCoreCLI@2
  displayName: 'Publish Project - $(buildConfiguration)'
  inputs:
    command: publish
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
    projects: '**/*.csproj'
    zipAfterPublish: true
    publishWebProjects: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()